#!/bin/bash

# Importing variables config
source "/etc/cloudinit/variables.sh"

# Global variables
export CI_INTERACTIVE=0
export CI_ON_BOOT=0
export CI_START=0
usage() {
    echo ""
    echo "Usage: $0 --name <VM_name> --ip <ip_address> [--option]"
    echo "  --id            ID of the VM (Default: automatically choose the first available ID)"
    echo "  --cpu           CPU count (Default: $CI_CPU)"
    echo "  --name          VM name (Default: $CI_VM_NAME)"
    echo "  --ram           RAM size un MB (Default: $CI_RAM)"
    echo "  --disk          disk size (Default: $CI_DISK)"
    echo "  --cidr          CIDR of the network (Default: $CI_CIDR)"
    echo "  --ip            IP Address used for networking (Required unless interactive)"
    echo "  --gateway       IP address of the gateway (Default: $CI_GATEWAY)"
    echo "  --dns           IP address of the DNS servers (Defaut: $CI_DNS)"
    echo "  --os            Operating system used on for the VM (Defaut: $CI_OS)"
    echo "  --listos        List the available operating systems"
    echo "  --rp            Root password (Default: $CI_ROOT_PASSWORD)"
    echo "  --user          Username (Defaut: $CI_USER_NAME)"
    echo "  --up            User password (Defaut: $CI_USER_PASSWORD)"
    echo "  --onboot        Start with Proxmox (Defaut: Disabled)"
    echo "  --start         Start the VM (Defaut: Disabled)"
    echo "  --backup        Put the VM in a backup procedure (Defaut: Disabled)"
    echo "  --backupid      ID of the backup procedure (Required if backup enabled)"
    echo "  --listbackupids Lists all the backup procedures"
    echo "  --interactive   Interactive mode"
    exit 1
}

installJq() {
    # Verifies if jq is not installed
if ! command -v jq &> /dev/null; then
    echo "jq is not installed. Installing jq..."
    apt-get update -y > /dev/null
    apt-get install jq -y > /dev/null
   

    # Vérifie si l'installation a réussi
    if command -v jq &> /dev/null; then
        echo "jq was installed successfully!"
    else
        echo "jq installation failed, please cheq manually"
        exit 1
    fi
fi
}

listBackupIds() {
    installJq
    echo "Backup procedure available:"
    echo "$(pvesh get /cluster/backup --output-format json | jq -r '.[] | "\(.id): \(.comment // "No comment.")"')"
}

CI_SCRIPTS_VAR=("$CI_SCRIPTS"/*.sh)

listOS() {
    for i in "${!CI_SCRIPTS_VAR[@]}"; do
        CI_FILE_NAME=$(basename "${CI_SCRIPTS_VAR[$i]}" .sh)
        echo "$((i + 1))) $CI_FILE_NAME"
    done
}

convert_to_mb() {
  input="$1"
  value=""
  unit=""

  # Extraire la partie numérique et la partie unité (insensible à la casse)
  if [[ "$input" =~ ^([0-9]+)([a-zA-Z]*)$ ]]; then
    value="${BASH_REMATCH[1]}"
    unit="${BASH_REMATCH[2]}"
    unit="${unit^^}"  # Met en majuscules
  else
    echo "Format invalide: $input" >&2
    return 1
  fi

  # Conversion selon l’unité
  case "$unit" in
    ""|"M"|"MB")
      echo "$value"
      ;;
    "G"|"GB")
      echo $((value * 1024))
      ;;
    *)
      echo "Unité inconnue: $unit" >&2
      return 1
      ;;
  esac
}

# Parsing des arguments
while [[ $# -gt 0 ]]; do
    case "$1" in
        --id) CI_VM_ID="$2"; shift 2 ;;
        --name) CI_VM_NAME="$2"; shift 2 ;;
        --cpu) CI_CPU="$2"; shift 2 ;;
        --ram) CI_RAM="$2"; shift 2 ;;
        --disk) CI_DISK="$2"; shift 2 ;;
        --cidr) $CI_CIDR="$2"; shift 2 ;;
        --ip) CI_IP_ADDRESS="$2"; shift 2 ;;
        --gateway) CI_GATEWAY="$2"; shift 2 ;;
        --dns) CI_DNS="$2"; shift 2 ;;
        --os) CI_OS="$2"; shift 2 ;;
        --listos) listOS; exit 1; shift;;
        --rp) CI_ROOT_PASSWORD="$2"; shift 2 ;;
        --user) CI_USER_NAME="$2"; shift 2 ;;
        --up) CI_USER_PASSWORD="$2"; shift 2 ;;
        --interactive) CI_INTERACTIVE=1; shift ;;
        --onboot) CI_ON_BOOT=1; shift ;;
        --start) CI_START=1; shift ;;
        --backup) CI_BACKUP=1; shift; installJq ;;
        --backupid) CI_BACKUP_ID="$2"; shift 2 ;;
        --listbackupids) listBackupIds; exit 1; shift;;
        --) shift; break ;;
        *) usage;
    esac
done

CI_NETWORK=$($CI_UTILS/networking.sh "$CI_NETWORK/$CI_CIDR" NETWORK)
freeRandomIP() {
    CI_TRIED_IPS=$1
    CI_TRIED_IPS="${CI_TRIED_IPS:-0}"
    CI_USABLE_IPS=$($CI_UTILS/networking.sh "$CI_NETWORK/$CI_CIDR" USABLE)
    if [ "$CI_TRIED_IPS" -ge $CI_USABLE_IPS ]; then
        echo "No free IP on this network... please check, maybe some cleanup is necessary"
        exit 1
    fi
    CI_RANDOM_IP=$($CI_UTILS/networking.sh "$CI_NETWORK/$CI_CIDR" RANDOM)
    if [ -f "$CI_NETWORKS/$CI_NETWORK/$CI_RANDOM_IP" ]; then
        freeRandomIP $((CI_TRIED_IPS + 1))
    else
        echo $CI_RANDOM_IP
    fi
}

# Defaults to the next available id in Proxmox
CI_VM_ID="${CI_VM_ID:-$(pvesh get /cluster/nextid)}"

CI_IP_ADDRESS="${CI_IP_ADDRESS:-$(freeRandomIP)}"
interactiveStepID() {
    read -p "What ID would you like to give to the VM? (currently $CI_VM_ID) >" CI_CHOICE
    CI_VM_ID=${CI_CHOICE:-$CI_VM_ID}
}

interactiveStepName() {
    read -p "What name would you like to give to the VM? (Currently $CI_VM_NAME) >" CI_CHOICE
    CI_VM_NAME=${CI_CHOICE:-$CI_VM_NAME}
}

interactiveStepOS() {
    echo "What OS would you like to use on the VM?"
    listOS
    echo "0) Cancel"
    echo
    read -p ">" CI_CHOICE
    if [[ "$CI_CHOICE" == "0" ]]; then
        echo "Cancelled."
        exit 0
    elif [[ "$CI_CHOICE" =~ ^[0-9]+$ ]] && (( CI_CHOICE >= 1 && CI_CHOICE <= ${#CI_SCRIPTS_VAR[@]} )); then
        CI_OS_SCRIPT="${CI_SCRIPTS_VAR[$((CI_CHOICE - 1))]}"
        CI_OS_NAME=$(basename "$CI_OS_SCRIPT" .sh)
    else
        echo "Invalid choice."
        interactiveStepOS
    fi
}

interactiveStepCPU() {
    read -p "How many CPU cores would you like to give to your VM? (Currently $CI_CPU) >" CI_CHOICE
    CI_CPU=${CI_CHOICE:-$CI_CPU}
}

interactiveStepRAM() {
    read -p "How much RAM would you like to give to your VM? (Currently $CI_RAM) >" CI_CHOICE
    CI_RAM=${CI_CHOICE:-$CI_RAM}
    CI_RAM_MB=$(convert_to_mb "$CI_RAM")
}

interactiveStepDisk() {
    read -p "How much disk space would you like to give to your VM? (Currently $CI_DISK) >" CI_CHOICE
    CI_DISK=${CI_CHOICE:-$CI_DISK}
}

interactiveStepNetwork() {
    read -p "Do you want to add networking to the VM? ([Y]/N) >" CI_CHOICE
    echo $CI_CHOICE
    CI_CHOICE=${CI_CHOICE:-"Y"}
    CI_CHOICE="${CI_CHOICE^^}"
    echo $CI_CHOICE

    if [[ $CI_CHOICE == "Y" ]] then
        read -p "What network would you like to set your VM into? (Currently $CI_NETWORK) >" CI_CHOICE
        CI_NETWORK=${CI_CHOICE:-$CI_NETWORK}
        read -p "What is the CIDR of your VM? (Currently $CI_CIDR) >" CI_CHOICE
        CI_CIDR=${CI_CHOICE:-$CI_CIDR}
        read -p "What IP would you like to give your VM? (Currently $CI_IP_ADDRESS) >" CI_CHOICE
        CI_IP_ADDRESS=${CI_CHOICE:-$CI_IP_ADDRESS}
    elif [[ $CI_CHOICE == "N" ]] then
        echo
    else
        echo "Please reply by Y or N"
        interactiveStepNetwork
    fi
}

interactiveMode() {
    interactiveStepID
    interactiveStepName
    interactiveStepOS
    interactiveStepCPU
    interactiveStepRAM
    interactiveStepDisk
    interactiveStepNetwork

    export $CI_VM_ID
    export $CI_VM_NAME
    export $CI_OS_NAME
    export $CI_OS_SCRIPT
    export $CI_CPU
    export $CI_RAM
    export $CI_RAM_MB
    export $CI_DISK
    export $CI_CHOICE
    export $CI_NETWORK
    export $CI_CIDR
    export $CI_IP_ADDRESS

    $CI_OS_SCRIPT
    exit 0
}

if [[ $CI_INTERACTIVE -eq 1 ]]; then
    interactiveMode
else
    echo "TODO: args checking"
    echo "use interactive mode for now."
    exit 1
fi

echo "What OS would you like to use?"
echo

# Show the menu
for i in "${!CI_SCRIPTS_VAR[@]}"; do
    CI_FILE_NAME=$(basename "${CI_SCRIPTS_VAR[$i]}" .sh)
    echo "$((i + 1))) $CI_FILE_NAME"
done

echo "0) Cancel"
echo
read -p "> " CI_CHOICE

# Gérer le choix
if [[ "$CI_CHOICE" == "0" ]]; then
    echo "Cancelled."
    exit 0
elif [[ "$CI_CHOICE" =~ ^[0-9]+$ ]] && (( CI_CHOICE >= 1 && CI_CHOICE <= ${#CI_SCRIPTS_VAR[@]} )); then
    CI_SCRIPT="${CI_SCRIPTS_VAR[$((CI_CHOICE - 1))]}"
    echo "Starting $CI_SCRIPT..."
    bash "$CI_SCRIPT"
else
    echo "Invalid choice."
    exit 1
fi

echo "TODO"